### ISSUE TITLE
Error: Invalid property for defaults:compressed

### ISSUE THREAD

**Issue by bestpika** [rchipka/node-osmosis#241]
```javascript
'use strict'
const osmosis = require('osmosis')
```

```
Error: Invalid property for defaults:compressed
    at Function.module.exports.defaults (D:\tmp\n0use-api-heroku-nodejs\node_modules\libxmljs-dom\node_modules\needle\lib\needle.js:776:13)
    at Object.<anonymous> (D:\tmp\n0use-api-heroku-nodejs\node_modules\libxmljs-dom\lib\HttpRequest.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\tmp\n0use-api-heroku-nodejs\node_modules\libxmljs-dom\lib\Window.js:8:22)
```

**Comment by bestpika** [comment]
Use npm/pnpm install dep and the bug will go.

**Comment by ggomez91** [comment]
@roytz It worked for me. use these settings in your package.json:
`
  "dependencies": {
    "needle": "2.3.0",
    "osmosis": "^1.1.10"
  },
  "resolutions": {
    "needle": "2.3.0"
  }
`


I think this is a bug in the dependencies, right?

**Comment by fortydegrees** [comment]
I get the same issue, tried changing package.json and no luck. using node v8.10.0

**Comment by fortydegrees** [comment]
I re-installed and got it running, but now I can't load a page and just get:

TypeError: fs.readdirSync is not a function

**Comment by CanRau** [comment]
Can't get it working, installed needle and osmosis multiple time. I'm on Node v10.16.3

**Comment by dbshell** [comment]
Problem is in library libxmljs-dom, it worked with needle 2.3.0, but doesn't work with needle 2.4.0. If I add package neddle@2.3.0 and manually delete needle from node_modules in libxmljs-dom directory, than it works. There is 6 months old pull request on github https://github.com/libxmljs/libxmljs-dom/pull/11 , which solves this, but nobody has accepted it. I am not sure, how to solve this systematically.

**Comment by wxs77577** [comment]
Same issue today.
